config/routes.rb
HydraHead::Application.routes.draw do

  resources :paper_languages
  resources :paper_types
  resources :institutes
  resources :papers
  resources :downloads, :only => "show"

  root :to => "catalog#index"

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  devise_for :users

  match '/login',                   :to => 'users/sessions#new',       :as => 'new_user_session'
  match '/auth/:provider/callback', :to => 'users/sessions#create',    :as => 'create_user_session'
  match '/logout',                  :to => 'users/sessions#destroy',   :as => 'destroy_user_session'

  match '/faq',                     :to => 'catalog#index'
  match '/kontakt',                 :to => 'catalog#index'

  match '/admin/rebuild',           :to => 'papers#reloadsolrindex'

end

app/models/institute.rb
class Institute < ActiveRecord::Base
  attr_accessible :description, :order, :title
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  # GET /institutes
  # GET /institutes.json
  def index
    @institutes = Institute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutes }
    end
  end

  # GET /institutes/1
  # GET /institutes/1.json
  def show
    @institute = Institute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institute }
    end
  end

  # GET /institutes/new
  # GET /institutes/new.json
  def new
    # only admins are allowed to create new institutes
    #authorize! :admin, @all
    @institute = Institute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @institute }
    end
  end

  # GET /institutes/1/edit
  def edit
    #authorize! :admin, @all
    @institute = Institute.find(params[:id])
  end

  # POST /institutes
  # POST /institutes.json
  def create
    #authorize! :admin, @all
    @institute = Institute.new(params[:institute])

    respond_to do |format|
      if @institute.save
        format.html { redirect_to @institute, notice: 'Institute was successfully created.' }
        format.json { render json: @institute, status: :created, location: @institute }
      else
        format.html { render action: "new" }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /institutes/1
  # PUT /institutes/1.json
  def update
    #authorize! :admin, @all
    @institute = Institute.find(params[:id])

    respond_to do |format|
      if @institute.update_attributes(params[:institute])
        format.html { redirect_to @institute, notice: 'Institute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutes/1
  # DELETE /institutes/1.json
  def destroy
    #authorize! :admin, @all
    @institute = Institute.find(params[:id])
    @institute.destroy

    respond_to do |format|
      format.html { redirect_to institutes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/_form.html.erb
<%= form_for @institute, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                institutes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/institutes/edit.html.erb
<%- model_class = Institute -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/institutes/index.html.erb
<%- model_class = Institute -%>
<div class="page-header">
  <h1>Studium</h1>
  <p>
    Liste over studier
  </p>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @institutes.each do |institute| %>
      <tr>
        <td><%= link_to institute.id, institute_path(institute) %></td>
        <td><%= institute.title %></td>
        <td><%= institute.created_at %></td>
        <td>
          <% if can? :manage, @institutes    %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_institute_path(institute), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      institute_path(institute),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% else %>
          <p>Kun for administratorer</p>
           <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :manage, @institutes    %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_institute_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/institutes/new.html.erb
<%- model_class = Institute -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/institutes/show.html.erb
<%- model_class = Institute -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @institute.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order) %>:</strong></dt>
  <dd><%= @institute.order %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @institute.description %></dd>
</dl>


<div class="form-actions">

  <%= link_to t('.back', :default => t("helpers.links.back")),
              institutes_path, :class => 'btn'  %>
  <% if can? :manage, @institutes    %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_institute_path(@institute), :class => 'btn' %>

  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              institute_path(@institute),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>