config/routes.rb
HydraHead::Application.routes.draw do

  resources :paper_languages
  resources :paper_types
  resources :institutes
  resources :papers
  resources :downloads, :only => "show"

  root :to => "catalog#index"

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  devise_for :users

  match '/login',                   :to => 'users/sessions#new',       :as => 'new_user_session'
  match '/auth/:provider/callback', :to => 'users/sessions#create',    :as => 'create_user_session'
  match '/logout',                  :to => 'users/sessions#destroy',   :as => 'destroy_user_session'

  match '/faq',                     :to => 'catalog#index'
  match '/kontakt',                 :to => 'catalog#index'

  match '/admin/rebuild',           :to => 'papers#reloadsolrindex'

end

app/models/paper_language.rb
class PaperLanguage < ActiveRecord::Base
  attr_accessible :description, :order, :title
end

app/controllers/paper_languages_controller.rb
class PaperLanguagesController < ApplicationController
  # GET /paper_languages
  # GET /paper_languages.json
  def index
    @paper_languages = PaperLanguage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paper_languages }
    end
  end

  # GET /paper_languages/1
  # GET /paper_languages/1.json
  def show
    @paper_language = PaperLanguage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper_language }
    end
  end

  # GET /paper_languages/new
  # GET /paper_languages/new.json
  def new
    @paper_language = PaperLanguage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper_language }
    end
  end

  # GET /paper_languages/1/edit
  def edit
    @paper_language = PaperLanguage.find(params[:id])
  end

  # POST /paper_languages
  # POST /paper_languages.json
  def create
    @paper_language = PaperLanguage.new(params[:paper_language])

    respond_to do |format|
      if @paper_language.save
        format.html { redirect_to @paper_language, notice: 'Paper language was successfully created.' }
        format.json { render json: @paper_language, status: :created, location: @paper_language }
      else
        format.html { render action: "new" }
        format.json { render json: @paper_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paper_languages/1
  # PUT /paper_languages/1.json
  def update
    @paper_language = PaperLanguage.find(params[:id])

    respond_to do |format|
      if @paper_language.update_attributes(params[:paper_language])
        format.html { redirect_to @paper_language, notice: 'Paper language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paper_languages/1
  # DELETE /paper_languages/1.json
  def destroy
    @paper_language = PaperLanguage.find(params[:id])
    @paper_language.destroy

    respond_to do |format|
      format.html { redirect_to paper_languages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/paper_languages_helper.rb
module PaperLanguagesHelper
end

app/views/paper_languages/_form.html.erb
<%= form_for @paper_language, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                paper_languages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/paper_languages/edit.html.erb
<%- model_class = PaperLanguage -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/paper_languages/index.html.erb
<%- model_class = PaperLanguage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @paper_languages.each do |paper_language| %>
      <tr>
        <td><%= link_to paper_language.id, paper_language_path(paper_language) %></td>
        <td><%= paper_language.title %></td>
        <td><%= paper_language.description %></td>
        <td><%=l paper_language.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_paper_language_path(paper_language), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      paper_language_path(paper_language),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_paper_language_path,
            :class => 'btn btn-primary' %>

app/views/paper_languages/new.html.erb
<%- model_class = PaperLanguage -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/paper_languages/show.html.erb
<%- model_class = PaperLanguage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @paper_language.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order) %>:</strong></dt>
  <dd><%= @paper_language.order %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @paper_language.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              paper_languages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_paper_language_path(@paper_language), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              paper_language_path(@paper_language),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>