config/routes.rb
HydraHead::Application.routes.draw do

  resources :paper_languages
  resources :paper_types
  resources :institutes
  resources :papers
  resources :downloads, :only => "show"

  root :to => "catalog#index"

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  devise_for :users

  match '/login',                   :to => 'users/sessions#new',       :as => 'new_user_session'
  match '/auth/:provider/callback', :to => 'users/sessions#create',    :as => 'create_user_session'
  match '/logout',                  :to => 'users/sessions#destroy',   :as => 'destroy_user_session'

  match '/faq',                     :to => 'catalog#index'
  match '/kontakt',                 :to => 'catalog#index'

  match '/admin/rebuild',           :to => 'papers#reloadsolrindex'

end

app/views/shared/_footer.html.erb
<div class="push"><!--//--></div>
<footer>
    <div class="container">
      <p>
        <a href="http://www.kb.dk" class="kb"></a>
        <a href="http://www.srku.dk" class="srku"></a>
      </p>
        <%= raw t('dias.footer') %>


    </div>
</footer>

<% if can? :manage, @alle   %>
    <div class="navbar navbar-fixed-bottom navbar-inverse admin">

      <div class="navbar-inner">

        <div class="container">

          <a class="brand" href="#"><i class="icon-cog icon-white"></i> Administrator</a>
          <ul class="nav">
            <li class="divider-vertical"></li>
            <li>
              <%=  link_to 'Se alle opgaver',papers_path %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%=  link_to 'Liste over studier',institutes_path %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%=  link_to 'Liste over sprog',paper_languages_path %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%=  link_to 'Liste over opgave typer',paper_types_path %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%=  link_to 'Genbyg solr søgeindex',admin_rebuild_path  %>
            </li>



            <li class="divider-vertical"></li>
          </ul>

        </div>

      </div>

    </div>


<% end  %>

<%= render :partial => 'layouts/ga' if Rails.env.production? %>

app/views/shared/_header_navbar.html.erb
<div class="navbar navbarDias">
  <div class="navbar-inner">
    <div class="container">

        <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <%if I18n.locale.to_s=="en" %>
            <a href="<%=root_path%>" title="<%=application_name%>" class="brand langUk"></a>
        <%else%>
            <a href="<%=root_path%>" title="<%=application_name%>" class="brand langDa"></a>
        <%end%>

        <div class="nav-collapse collapse">
            <ul class="nav ">

                  <% if can? :create, Paper   %>
                  <li><%= link_to t('.new', :default => raw(t('dias.views.forside.tilfoejknap'))),
                                     new_paper_path %></li>
                  <% end %>




                <li>
                    <%= render :partial=>'/user_util_links' %>
                </li>
                <li>
                     <%=  link_to t('dias.views.faq.overskrift'), faq_path  %>
                </li>


              <li>
                <%=  link_to t('dias.views.kontakt.overskrift'), kontakt_path %>
              </li>
                <li>
                    <%if I18n.locale.to_s=="en" %>
                        <%= link_to t('dias.changelang'), {:locale=>"da"} %>
                    <%else%>
                        <%= link_to t('dias.changelang'), {:locale=>"en"} %>
                    <%end%>
                </li>
                <li>
                    <%if I18n.locale.to_s=="en" %>
                        <%= link_to t('dias.cookiepolicy'), 'http://www.kb.dk/en/kb/webstedet/cookiepolitik.html',:class => 'cookie' %>
                    <%else%>
                        <%= link_to t('dias.cookiepolicy') , 'http://www.kb.dk/da/kb/webstedet/cookiepolitik.html',:class => 'cookie' %>
                    <%end%>
                </li>
            </ul>
        </div>

    </div>
  </div>
</div>

<div id="searchWrapper">
    <%= render_search_bar  %>
</div>