config/routes.rb
HydraHead::Application.routes.draw do

  resources :paper_languages
  resources :paper_types
  resources :institutes
  resources :papers
  resources :downloads, :only => "show"

  root :to => "catalog#index"

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  devise_for :users

  match '/login',                   :to => 'users/sessions#new',       :as => 'new_user_session'
  match '/auth/:provider/callback', :to => 'users/sessions#create',    :as => 'create_user_session'
  match '/logout',                  :to => 'users/sessions#destroy',   :as => 'destroy_user_session'

  match '/faq',                     :to => 'catalog#index'
  match '/kontakt',                 :to => 'catalog#index'

  match '/admin/rebuild',           :to => 'papers#reloadsolrindex'

end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController

  include Blacklight::Catalog
  include Hydra::Controller::ControllerBehavior
  # These before_filters apply the hydra access controls
  #before_filter :enforce_show_permissions, :only=>:show
  # This applies appropriate access controls to all solr queries
  #CatalogController.solr_search_params_logic += [:add_access_controls_to_solr_params]
  # This filters out objects that you want to exclude from search results, like FileAssets
  # :exclude_unwanted_models << 'info:fedora/afmodel:Image'
  CatalogController.solr_search_params_logic += [:exclude_unwanted_models]
  #CatalogController.solr_search_params_logic += [:exclude_unwanted_models]
  #CatalogController.solr_search_params_logic.delete('active_fedora_model_ssi:Paper')


  configure_blacklight do |config|
    logger.info("### configure_blacklight i sproget I18n.locale=" + I18n.locale.to_s + " locale=" + :locale.to_s)
    config.default_solr_params = {
      :qf => 'title_tesim undertitel_tesim abstrakt_tesim name_namePart_tesim forfatter_tesim',
      :qt => 'search',
      :fq => 'active_fedora_model_ssi:Paper',
      #-active_fedora_model_ssi:Image
      #:search_field => 'all_fields',
      :rows => 20
    }

    # solr field configuration for search results/index views
    config.index.show_link = 'title_tesim'
    config.index.record_display_type = 'has_model'

    # solr field configuration for document/show views
    config.show.html_title = 'title_tesim'
    config.show.heading = 'title_tesim'
    config.show.display_type = 'has_model'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _tsimed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #config.add_facet_field 'object_type_facet', :label => 'Format'
    #config.add_facet_field 'pub_date', :label => 'Publication Year'
    #config.add_facet_field 'subject_topic_facet', :label => 'Topic', :limit => 20
    #config.add_facet_field 'language_facet', :label => 'Language', :limit => true
    #config.add_facet_field 'lc_1letter_facet', :label => 'Call Number'
    #config.add_facet_field 'subject_geo_facet', :label => 'Region'
    #config.add_facet_field 'subject_era_facet', :label => 'Era'
    config.add_facet_field 'studium_tesim', :label => I18n.t('dias.views.forside.labels.studium') , :limit => 7
    config.add_facet_field 'afleveringsaar_tesim', :label => I18n.t('dias.views.forside.labels.afleveringsaar'),  :limit => 7
    config.add_facet_field 'opgavesprog_tesim', :label => I18n.t('dias.views.forside.labels.opgavesprog')#, :limit => 7
    config.add_facet_field 'opgavetype_tesim', :label => I18n.t('dias.views.forside.labels.opgavetype') #, :limit => 7

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys
    #use this instead if you don't want to query facets marked :show=>false
    #config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys


    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field 'title_tesim', :label => I18n.t('dias.views.forside.labels.title')
    config.add_index_field 'title_vern_display', :label => I18n.t('dias.views.forside.labels.title')

    config.add_index_field 'undertitel_tesim', :label => I18n.t('dias.views.forside.labels.undertitel')
    config.add_index_field 'undertitel_vern_tesim', :label => I18n.t('dias.views.forside.labels.undertitel')

    config.add_index_field 'forfatter_tesim', :label => I18n.t('dias.views.forside.labels.forfatter')
    config.add_index_field 'forfatter_vern_tesim', :label => I18n.t('dias.views.forside.labels.forfatter')

    config.add_index_field 'afleveringsaar_tesim', :label => I18n.t('dias.views.forside.labels.afleveringsaar')
    config.add_index_field 'afleveringsaar_vern_tesim', :label => I18n.t('dias.views.forside.labels.afleveringsaar')



    config.add_index_field 'opgavetype_tesim', :label => I18n.t('dias.views.forside.labels.opgavetype')
    config.add_index_field 'opgavetype_vern_tesim', :label => I18n.t('dias.views.forside.labels.opgavetype')


    #config.add_index_field 'author_vern_display', :label => 'Author:'
    #config.add_index_field 'format', :label => 'Format:'
    #config.add_index_field 'language_facet', :label => 'Language:'
    #config.add_index_field 'published_display', :label => 'Published:'
    #config.add_index_field 'published_vern_display', :label => 'Published:'
    #config.add_index_field 'lc_callnum_display', :label => 'Call number:'

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field 'title_tesim', :label => I18n.t('dias.views.forside.labels.title')
    config.add_show_field 'undertitel_display', :label => I18n.t('dias.views.forside.labels.undertitel')

    #config.add_show_field 'title_vern_display', :label => 'Title:'
    #config.add_show_field 'subtitle_display', :label => 'Subtitle:'
    #config.add_show_field 'subtitle_vern_display', :label => 'Subtitle:'
    config.add_show_field 'forfatter_tesim', :label => I18n.t('dias.views.forside.labels.forfatter')


    config.add_show_field 'afleveringsaar_tesim', :label => I18n.t('dias.views.forside.labels.afleveringsaar')


    config.add_show_field 'studium_tesim', :label => I18n.t('dias.views.forside.labels.studium')

    config.add_show_field 'opgavesprog_tesim', :label => I18n.t('dias.views.forside.labels.opgavesprog')
    config.add_show_field 'genre_tesim', :label => I18n.t('dias.views.forside.labels.opgavetype')


    config.add_show_field 'abstrakt_tesim', :label => I18n.t('dias.views.forside.labels.abstrakt')

    #config.add_show_field 'author_vern_display', :label => 'Author:'
    #config.add_show_field 'format', :label => 'Format:'
    #config.add_show_field 'url_fulltext_display', :label => 'URL:'
    #config.add_show_field 'url_suppl_display', :label => 'More Information:'
    #config.add_show_field 'language_facet', :label => 'Language:'
    #config.add_show_field 'published_display', :label => 'Published:'
    #config.add_show_field 'published_vern_display', :label => 'Published:'
    #config.add_show_field 'lc_callnum_display', :label => 'Call number:'
    #config.add_show_field 'isbn_t', :label => 'ISBN:'


    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different.

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise.

    config.add_search_field 'all_fields', :label => I18n.translate('dias.views.forside.allefelter') #'Alle Felter' #


    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields.

    config.add_search_field('Titel') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params.
      field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      #field.solr_local_parameters = {
      #  :qf => '$title_qf',
      #  :pf => '$title_pf'
      #}
    end

=begin
    config.add_search_field('author') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'author' }
      field.solr_local_parameters = {
        :qf => '$author_qf',
        :pf => '$author_pf'
      }
    end
=end


    config.add_search_field('Forfatter') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'forfatter' }
      field.solr_local_parameters = {
          :qf => '$forfatter_qf',
          :pf => '$forfatter_pf'
      }

app/views/catalog/_bookmark_control.html.erb
<!-- nej tak til bogmærker, og æselører.-->

app/views/catalog/_document.html.erb
<% # container for a single doc  -%>
<div class="document <%= render_document_class document %>">

  <%= render :partial => 'document_header', :locals => {:document => document, :document_counter => document_counter} %>

  <% # main container for doc partial view  -%>
  <% # render_document_partial document, :index  %>
  <dl class="dl-horizontal dl-invert">

    <% if document["undertitel_t"] %>
        <dt class="blacklight-undertitel_t"><%= t('dias.views.paper.labels.undertitel') %></dt>
        <dd class="blacklight-undertitel_t"><%= document["undertitel_tesim"].first.html_safe rescue nil %></dd>
    <% end %>

    <dt class="blacklight-forfatter_t"><%= t('dias.views.paper.labels.forfatter') %></dt>
    <dd class="blacklight-forfatter_t"><%= document["forfatter_tesim"].to_sentence.html_safe rescue nil %></dd>

    <dt class="blacklight-afleveringsaar_t"><%= t('dias.views.paper.labels.afleveringsaar') %></dt>
    <dd class="blacklight-afleveringsaar_t"><%= document["afleveringsaar_tesim"].first.html_safe rescue nil %></dd>

    <dt class="blacklight-opgavetype_t"><%= t('dias.views.paper.labels.opgavetype') %></dt>
    <dd class="blacklight-opgavetype_t"><%= document["opgavetype_tesim"].first.html_safe rescue nil %></dd>


    <dt><%= t('dias.views.paper.labels.pdffil') %></dt>
    <dd><%= link_to document["title_tesim"].first.html_safe, download_path(document["id"]) %></dd>


    <dt><%= t('dias.views.paper.labels.licens') %></dt>
    <% if document["licens_description_tesim"] %>
        <dd>
          <%= raw document["licens_description_tesim"].first.html_safe %>
          <!--a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.da"><img alt="Creative Commons licens" src="http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png"/></a-->
        </dd>
    <% else %>
        <dd>ingen licens defineret&nbsp;</dd>
    <% end %>
  </dl>
</div>

app/views/catalog/_facet_limit.html.erb
<ul>
  <% paginator =
      Blacklight::Solr::FacetPaginator.new(display_facet.items,
        :limit => facet_limit_for(solr_field))
  %>
  <% paginator.items.each do |item| -%>
    <li>
    <% if facet_in_params?( solr_field, item.value ) %>
        <%= render_selected_facet_value(solr_field, item) %>
      <% else %>
        <%= render_facet_value(solr_field, item) %>
    <% end -%>
    </li>
  <% end %>

  <% if(paginator.has_next?)  %>
    <li class="more_facets_link"><%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %></li>
  <% end %>

</ul>

app/views/catalog/_facets.html.erb
<% # main container for facets/limits menu -%>
<% if has_facet_values?  %>
    <div id="facets" class="facets" >
      <div id="facets-collapse"  style="display:none">

        <%= render_facet_partials %>
      </div>
    </div>


<% end %>

app/views/catalog/_home.html.erb
<% #Search form can be added here, defaulted to the navbar for Bootstrap version -%>
<%= render :partial=>'home_text' %>

<% sidebar_items << capture do %>
  <%= render :partial=>'facets' %>
<% end %>

app/views/catalog/_home_text.html.erb
<div class="row">

    <div class="span9 teaser">
        <div class="imgContent">
            <%= image_tag "dias/teaserImg.jpg" , :alt => "Edit Entry" %>

          <div>
            <%= raw t('dias.views.forside.velkommen') %>
          </div>

        </div>

      <p>
        <span> <%= t('dias.views.forside.samarbejdetext') %></span>
        <a href="http://www.srku.dk">
            <%= image_tag "dias/srkuLogo.png" , :alt => "Edit Entry" %>
        </a>
        <span>
          <%=raw t('dias.views.forside.forklaring') %>

        </span>
      </p>
    </div>




  <div class="span3 login">

      <h3>
        <%=raw t('dias.views.forside.text') %>
      </h3>

      <% if can? :create, Paper   %>
          <p><%= link_to t('.new', :default => raw(t('dias.views.forside.tilfoejknap'))),
                         new_paper_path,
                         :class => 'btn btn-large btn-success' %></p>
      <% end %>

      <% if cannot? :create, Paper   %>
          <p><%= link_to t('.new', :default => raw(t('dias.views.forside.tilfoejogloginknap'))),
                         new_user_session_path,
                         :class => 'btn btn-large btn-success', :id => 'big_login_button' %>   </p>
      <% end %>

    </div>


</div>

app/views/catalog/_search_form.html.erb
<div class="container">
    <div class="row">

        <div class="span8 offset2">

          <%= form_tag search_action_url, :method => :get, :class => "form-search" do %>
              <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>
              <%= hidden_field :search_field, :value => h(params["all_fields"])  %>

              <div class="input-prepend input-append">
                 <button type="button" class="btn btn-success btn-large"  onclick="$('#facets-collapse').slideToggle('slow')" >
                  <span><%= t('blacklight.search.facets.title') %></span><i class="icon-filter"></i>
                 </button>

                  <label for="q" class="hide-text"><%= t('blacklight.search.form.q') %></label>
                  <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "btn-large", :id => "q"%>

                  <button type="submit" class="btn btn-success btn-large" id="search">
                    <i class="icon-search"></i><span><%=t('blacklight.search.form.submit')%></span>
                  </button>

               </div>

            <% end %>
        </div>


    </div>
</div>

app/views/catalog/_show_sidebar.html.erb
<div class="well" id="sidebar-nav">
  <%= render :partial => 'show_tools' %>
</div><!--/well -->

<% unless @document.more_like_this.empty? %>
<div class="well" id="sidebar-mlt">
  <ul class="nav nav-list">
  <li class="nav-header">More Like This</li>
    <%= render :collection => @document.more_like_this, :partial => 'show_more_like_this', :as => :document %>
  </ul>
</div><!--/well -->
<% end %>

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

  #Added Bootstrap class well and 'hidden-phone' for the tools-bar 
-%>
  <ul class="nav nav-list">
      <li class="nav-header"><%= t('blacklight.tools.title') %></li>
      <li>
        <%= render_show_doc_actions @document %>
      </li>
      <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
        <li class="cite">
         <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :class => 'lightboxLink'} %>
        </li>
      <% end %>
      <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
        <li class="refworks">
        <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document)  %>        
        </li>
     <% end %>
     <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote') %>
      </li>
    <% end %>
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
      <%= link_to t('blacklight.tools.email'), email_catalog_path(:id => @document), {:id => 'emailLink', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    <%- if @document.respond_to?( :to_sms_text ) -%>
      <li class="sms">
      <%= link_to t('blacklight.tools.sms'), sms_catalog_path(:id => @document), {:id => 'smsLink', :class => 'lightboxLink'} %>
      </li>
    <%- end -%>
    
    <% if @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :class => 'lightboxLink'} %>
      </li>
    <% end %>
  </ul>

app/views/catalog/_sort_and_per_page.html.erb
<div id="sortAndPerPage">
   <div class="page_links">
     <%= render :partial => "paginate_compact" %>
   </div>
    <%= render :partial => 'sort_widget' %>


</div>

app/views/catalog/faq.html.erb
<div id="sidebar" class="span12">
  <%= render :partial=>'facets' %>
</div><!--/well -->


<div class="hero-unit">
  <h1><%= t('dias.views.faq.overskrift') %></h1>
  <p class="lead"><%=raw t('dias.views.faq.text') %></p>

</div>

app/views/catalog/index.html.erb
<div id="sidebar" class="span12">
    <%= render :partial=>'facets' %>
</div><!--/well -->


<div id="content" class="span12">

    <% #if !(has_search_parameters?) %>
    <% if (request.path=="/" || request.path=="/dias/") &&  !(has_search_parameters?) %>
	    <%# if there are no input/search related params, display the "home" partial -%>
	    <%= render 'home' %>
    <% elsif  request.path.to_s.include?('/faq')  %>

      <div class="faq">
        <h1><%= t('dias.views.faq.overskrift') %></h1>
        <%=raw t('dias.views.faq.text') %>

      </div>

  <% elsif  request.path.to_s.include?('/kontakt')  %>
      <div class="contact">
        <h1><%= t('dias.views.kontakt.overskrift') %></h1>
        <%=raw t('dias.views.kontakt.text') %>
      </div>
  <% elsif  has_search_parameters? %>

      <h2 class="hide-text top-content-title"><%= t('blacklight.search.search_results_header') %></h2>

      <% @page_title = t('blacklight.search.title', :application_name => application_name) %>


      <% extra_head_content << render_opensearch_response_metadata.html_safe %>

	    <%= render :partial => 'did_you_mean' %>

      <%= render :partial => 'constraints' %>

	    <%= render 'sort_and_per_page' %>

      <h2 class="hide-text"><%= t('blacklight.search.search_results') %></h2>
	    <%= render_document_index %>


	    <%= render 'results_pagination' %>

    <% else %>
      <%= render 'home' %>
    <% end %>


</div>

app/views/catalog/kontakt.html.erb
<div id="sidebar" class="span12">
  <%= render :partial=>'facets' %>
</div><!--/well -->


<div class="hero-unit">
  <h1><%= t('dias.views.kontakt.overskrift') %></h1>
  <p class="lead"><%=raw t('dias.views.kontakt.text') %></p>

</div>

app/views/catalog/show.html.erb
  <div id="content" class="span12 show-document">

    <%= render 'previous_next_doc' %>
     
  <% @page_title = t('blacklight.search.show.title', :document_title => document_show_html_title, :application_name => application_name) %>
  <% extra_head_content << render_link_rel_alternates %>
  <% sidebar_items << render_document_sidebar_partial %>

  <%# this should be in a partial -%>
  <div id="document" class="<%= render_document_class %>">
    <div id="doc_<%= @document.id.to_s.parameterize %>">


      <% # bookmark/folder functions -%>
      <%= render_document_heading(:h1).html_safe %>
      <h4><%= @document["undertitel_tesim"].first.html_safe if @document["undertitel_tesim"] %></h4>
      <div class="document">
      <dl>
        <dt><%=  t('dias.views.paper.labels.forfatter')  %></dt>
        <dd>
          <%#= @document["forfatter_t"].first.html_safe %>
              <%= @document["forfatter_tesim"].to_sentence.html_safe rescue nil %>
        </dd>
        <dt><%=  t('dias.views.paper.labels.afleveringsaar')  %></dt>
        <dd>
          <%= @document["afleveringsaar_tesim"].first.html_safe %>
        </dd>

        <dt><%=  t('dias.views.paper.labels.studium')  %></dt>
        <dd>
          <%= @document["studium_tesim"].first.html_safe %>
        </dd>


        <dt><%=  t('dias.views.paper.labels.abstrakt')  %></dt>
        <dd><blockquote>
          <%= simple_format( @document["abstrakt_tesim"].first, ) if @document["abstrakt_tesim"] %>
        </blockquote>
        </dd>

        <dt><%=  t('dias.views.paper.labels.opgavetype')  %></dt>
        <dd>
          <%= @document["genre_tesim"].first.html_safe %>
        </dd>

        <dt><%=  t('dias.views.paper.labels.opgavesprog')  %></dt>
        <dd>
          <%= @document["opgavesprog_tesim"].first.html_safe %>
        </dd>

        <dt><%=  t('dias.views.paper.labels.licens')  %></dt>
        <dd>
          <% if @document["licens_url"] %>
              <%= raw @document["licens_description"].html_safe  %>

              <!--
           <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.da"><img alt="Creative Commons licens" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png" /></a><br />Dette værk er licenseret under en <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.da">Creative Commons Navngivelse-IkkeKommerciel-IngenBearbejdelse 3.0 Unported Licens</a>.
              -->
          <% else %>
           ingen licens defineret&nbsp;
          <% end %>
        </dd>

        <dt>Download</dt>
        <dd>
          <%=  link_to 'PDF: '+ document_show_html_title, download_path(@document["id"]) %>

        </dd>
      </dl>


      </div>






    </div>
  </div>



    <% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
      <!-- 
           // COinS, for Zotero among others. 
           // This document_partial_name(@document) business is not quite right,
           // but has been there for a while. 
      -->
      <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(document_partial_name(@document)) %>"></span>
    <% end %>

  </div>